version: '3.8'

services:
  backend:
    image: ghcr.io/ccoupel/ansible-builder-backend:dev-1.9.0_2
    # For testing, use local image
    #image: ghcr.io/ccoupel/ansible-builder-backend:dev-1.9.0_2
    container_name: ansible-builder-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://ansible_user:ansible_password@ansible-db:5432/ansible_db
      - DEBUG=true
      - HOST=0.0.0.0
      - PORT=8000
    restart: unless-stopped
    networks:
      - ansiblebuilder_default
    external_links:
      - ansible-db:ansible-db

  frontend:
    image: ghcr.io/ccoupel/ansible-builder-frontend:dev-1.9.0_2
    container_name: ansible-builder-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - ansiblebuilder_default
    depends_on:
      - backend

networks:
  ansiblebuilder_default:
    external: true