apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "automation-factory.fullname" . }}-backend
  labels:
    {{- include "automation-factory.backend.labels" . | nindent 4 }}
data:
  cors-origins: {{ .Values.backend.env.CORS_ORIGINS | quote }}
