apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ansible-builder.fullname" . }}-backend
  labels:
    {{- include "ansible-builder.backend.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  postgres-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- else }}
  postgres-password: {{ .Values.postgresql.external.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  {{- if .Values.redis.auth.enabled }}
  redis-password: {{ .Values.redis.auth.password | b64enc | quote }}
  {{- end }}
  {{- else }}
  redis-password: {{ .Values.redis.external.password | b64enc | quote }}
  {{- end }}
  jwt-secret-key: {{ .Values.backend.env.JWT_SECRET_KEY | b64enc | quote }}
