apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ansible-builder.fullname" . }}-frontend
  labels:
    {{- include "ansible-builder.frontend.labels" . | nindent 4 }}
data:
  api-url: {{ .Values.frontend.env.VITE_API_URL | quote }}
